ardanlabs/service

README.md, cmd/crud/dockerfile
Improvements were made to the Dockerfile to isolate the build process to the Docker environment. This is utilizing a new Docker feature, [multi-staged builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/), that allows use of the `golang` image to build the container, and the `alpine` image to run it in.
While not utilized yet, you can also include a `build` global string, and this process will insert the current git commit hash into it. (Great for versioning too!)
=> Improved Dockerfile

internal/platform/docker/docker.go
+ Use 12 character IDs instead of 3. In testing I ran into collisions.
+ Don't need to `cmd.Wait` after `cmd.Run`. Since Run calls Wait.
+ Remove unnecessary string conversion
+ Prefer structure for `docker inspect` output over type assertions
=> Improve docker test commands

internal/platform/web/response.go
* Modified response method to write headers after marshaling has
succeeded
* Use ResponseWriter to write output.
=> Web Response

cmd/crud/main.go
This is the pattern we use in training. I prefer it because it allows the server to fail quickly if the listener can't bind such as when a port is in use.
=> Listen for errors starting the server

cmd/crud/handlers/health.go, cmd/crud/handlers/routes.go, cmd/crud/handlers/user.go, cmd/crud/main.go, cmd/crud/tests/tests_test.go, cmd/sidecar/metrics/main.go, cmd/sidecar/metrics/publisher/datadog/datadog.go, cmd/sidecar/metrics/publisher/expvar/expvar.go, cmd/sidecar/metrics/publisher/publisher.go, cmd/sidecar/tracer/handlers/health.go, cmd/sidecar/tracer/handlers/routes.go, cmd/sidecar/tracer/handlers/zipkin.go, cmd/sidecar/tracer/main.go, internal/mid/errors.go, internal/mid/logger.go, internal/mid/metrics.go, internal/platform/docker/docker.go, internal/platform/tests/main.go, internal/platform/web/response.go, internal/platform/web/web.go
Changes to remove the use of the stdlib singleton logger.
=> logging changes

docker-compose.yaml, dockerfile.crud, dockerfile.metrics, dockerfile.tracer, makefile
- Cleaned up Dockerfiles for current best practise
- Refactored makefile for new Dockerfiles / performance
=> Dockerfile best practises.

CONTRIBUTORS, README.md, internal/platform/trace/trace.go, internal/platform/trace/trace_test.go, internal/platform/web/web.go, vendor/go.opencensus.io/plugin/ochttp/propagation/tracecontext/propagation.go, vendor/go.opencensus.io/trace/propagation/propagation.go, vendor/modules.txt
This is using the trace propagration package from opencensus.
=> Changes for new trace propagation package

cmd/sales-api/handlers/routes.go, internal/mid/auth.go, internal/mid/errors.go, internal/mid/logger.go, internal/mid/metrics.go, makefile
Changes I identified during training.
=> readability and minor mistakes

cmd/sales-api/handlers/routes.go, internal/platform/web/middleware.go
Allowing the order to make sense.
=> fixing routes for better readability with middleware

internal/platform/web/web.go
=> missing ending  span at internal.platform.web

cmd/sales-api/handlers/product.go, cmd/sales-api/handlers/user.go, internal/mid/auth.go, internal/mid/errors.go, internal/mid/logger.go, internal/platform/web/errors.go, internal/platform/web/request.go, internal/platform/web/response.go
It still has been bothering me that there is no consistency in how we are handling errors, my mental models are off and bolierplate code was missing from the web package.
In not being able to sleep, I think I figured it out. Along the way, found another naming issue.
=> fixing idioms and mental models

cmd/sales-api/main.go
Calling `log.Fatal` before deferred code has ran can be problematic. Offloading most of the work to another function lets those defers finish.
We had discussed making `run` return an int. What I did instead was make `run` return an error and I am using `errors.Wrap` to document where failures occur. This seems like a more natural approach to me. Let's discuss.
=> Simplify main so defers are ran

.circleci/config.yml, internal/platform/database/databasetest/docker.go, internal/platform/database/databasetest/setup.go
This gets tests running in CircleCI. See https://circleci.com/gh/ardanlabs/service/18 for an example of a test run.
I also added an unexported helper function for debugging docker issues I encountered when setting this up.
I want to really talk about this approach and what changes we might need to make.
=> Run tests in CI

.circleci/config.yml
I made a comment about Go. Otherwise this is a start to changing the config over.
=> CI: Use machine executor.

README.md
This is some new documentation.
=> new documentation

business/data/product/product.go, business/data/user/user.go, business/mid/auth.go, business/mid/errors.go, business/mid/logger.go, business/mid/metrics.go, business/mid/panics.go, foundation/database/database.go, foundation/web/response.go, foundation/web/web.go
Issue : folder name  "internal" and "platform" was changed to "business" and "foundation", but tracer string was not updated. Sample in database.go  "platform.database.statuscheck" 
Fix: So changed  internal to business and platform to foundation. Sample  "foundation.database.statuscheck"
=> updated tracer info

CONTRIBUTORS, business/data/product/product.go, business/data/user/user.go
https://github.com/ardanlabs/service/issues/141
=> Wrap the error in user and product update

CONTRIBUTORS, app/sales-admin/commands/genkey.go
should be `publicFile` instead of `privateFile`.
=> fixed publicFile filename in keygen.go

CONTRIBUTORS, business/web/mid/auth.go, business/web/mid/cors.go, business/web/mid/errors.go, business/web/mid/logger.go, business/web/mid/metrics.go, business/web/mid/panics.go
What I did: I fixed the right path for tracing in the business middleware.
How did I fix it: I added the web folder path to the address, It was missing. `business/mid/....` to `business/web/mid....`
@ardan-bkennedy PTAL
=> fix the trace path in the middleware

makefile
Latest Kind `v0.11` brings breaking changes as well as support for both amd64 and arm64 in node images.
To update the project to be compatible with the latest Kind (but break compatibility with old versions) we need to use the node images from this [link](https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1). Using the latest node image from `dockerhub` is not compatible with Kind version >= 0.11, that's why having the comment in the makefile ensures that Kind and node version are in sync.
Furthermore, now we do not need the `make kind-up-m1` target, because the latest Kind and node image support arm64 besides amd64. (To be certain before considering merging the pull request someone with m1 mac should test it)
I also extracted the kind cluster name used: `ardan-starter-cluster` to …
=> Improves makefile and fixes latest Kind v0.11 breaking changes

business/data/product/product.go, business/data/user/user.go, business/sys/validate/validate.go, foundation/worker/worker.go
v1.2.0 release the NewString() function which is the equivalent of uuid.New().String().
=> NewString() is the equivalent of New().String()

CONTRIBUTORS, app/services/sales-api/handlers/handlers.go
Fixes https://github.com/ardanlabs/service/issues/195
=> Fix bug where headers weren't applied to OPTIONS call

.dockerignore, README.md, app/services/metrics/main.go, app/services/metrics/publisher/expvar/expvar.go, app/services/metrics/publisher/publisher.go, app/services/sales-api/handlers/debug/checkgrp/checkgrp.go, app/services/sales-api/handlers/handlers.go, app/services/sales-api/handlers/v1/productgrp/productgrp.go, app/services/sales-api/handlers/v1/usergrp/usergrp.go, app/services/sales-api/main.go, app/services/sales-api/tests/v1/user_test.go, business/core/product/db/db.go, business/core/product/product.go, business/core/user/db/db.go, business/core/user/user.go, business/sys/database/database.go, business/sys/metrics/metrics.go, business/sys/validate/errors.go, business/sys/validate/validate.go, business/web/v1/mid/auth.go, business/web/v1/mid/errors.go, foundation/keystore/keystore.go, foundation/logger/logger.go, foundation/web/web.go, foundation/worker/worker_test.go, makefile
I noticed a few typos and spelling errors while reading through the code.
=> chore: spelling errors

business/core/user/user.go, foundation/web/web.go
- Fixed using local time to UTC.
- Fixed typo.
=> Fixed using local time to UTC.

CONTRIBUTORS
=> Updated CONTRIBUTORS.

CONTRIBUTORS, business/sys/auth/auth.go, go.mod, go.sum, vendor/github.com/golang-jwt/jwt/v4/claims.go, vendor/github.com/golang-jwt/jwt/v4/errors.go, vendor/github.com/golang-jwt/jwt/v4/parser.go, vendor/github.com/golang-jwt/jwt/v4/parser_option.go, vendor/github.com/golang-jwt/jwt/v4/signing_method.go, vendor/github.com/golang-jwt/jwt/v4/token.go, vendor/github.com/golang-jwt/jwt/v4/types.go, vendor/modules.txt
Upgrade jwt package to 4.2
Remove depreciated type: https://pkg.go.dev/github.com/golang-jwt/jwt/v4#Parser
=> replace depreciated type

app/services/sales-api/handlers/v1/productgrp/productgrp.go
- Updated productgrp.go to have consistent error handling response.
=> Updated productgrp.go to have consistent error handling response.

business/sys/metrics/metrics.go
=> fixed typo

business/sys/metrics/metrics.go
=> Revert "fixed typo"

CONTRIBUTORS, makefile
Follow up after https://github.com/ardanlabs/euclass/pull/1
cc @ardan-bkennedy
=> Add make target to install Mac dev dependencies

business/data/dbschema/sql/seed.sql
in seed script field user_id is empty on table sales
=> fix missing field user_id

makefile
Hello, 
I'm just following along the course you guys made. And the binary names don't match. So I thought I just make a PR to fix it.
BTW interesting stuff and nice work with the repo 👍
=> update sales binary name

.circleci/config.yml, app/services/sales-api/handlers/v1/productgrp/productgrp.go, app/services/sales-api/handlers/v1/usergrp/filter.go, app/services/sales-api/handlers/v1/usergrp/usergrp.go, app/services/sales-api/main.go, app/services/sales-api/tests/v1/product_test.go, app/services/sales-api/tests/v1/user_test.go, app/tooling/sales-admin/commands/gentoken.go, app/tooling/sales-admin/commands/useradd.go, app/tooling/sales-admin/main.go, business/core/product/models.go, business/core/product/product.go, business/core/product/product_test.go, business/core/product/stores/productdb/models.go, business/core/product/stores/productdb/productdb.go, business/core/user/filter.go, business/core/user/models.go, business/core/user/stores/usercache/usercache.go, business/core/user/stores/userdb/models.go, business/core/user/stores/userdb/userdb.go, business/core/user/user.go, business/core/user/user_test.go, business/data/dbtest/dbtest.go, business/sys/database/database.go, business/sys/validate/validate.go, business/web/auth/auth.go, makefile, zarf/k8s/base/sales/base-sales.yaml
We have new rules on when the app layer performs validation and when the business layers does. This is to elminated extra validation in core to core business calls. Also using native UUID and Email types to reduce extra validation.
=> New validation rules

foundation/worker/worker.go
- Small tweak to use a `read lock` when checking if a work key exists in the `running` map.
- Added a `trackWork` helper method to minimize the locked lifetime which can possibly introduce contention when synchronizing a shutdown for a worker that takes awhile to finish.
=> Minimize or mitigate the chance of lock contention in worker.go

app/services/sales-api/main.go, foundation/logger/logger.go
This adds back the error logging for the http.Server
=> Add the log.Logger wrapper

foundation/web/web.go
Hi @ardan-bkennedy!
I noticed a small issue regarding the OpenTelemetry span management in the web framework:
Currently, the span is being created before there's a tracer in the context. As a result, the AddSpan only creates a new span, without actually starting it and attaching the received attributes. So, the solution is to construct the span and ctx before calling the AddSpan (similar to what happened before).
I also added an endpoint attribute, just thought it could be helpful.
=> Fix foundation.app.handle otel span

app/frontends/admin/src/app/dashboard/page.tsx, app/frontends/admin/src/context/UserContext.ts
For some reason this 2 files went untracked
=> fix bad push

makefile
Also, add some comments to make it clearer what we're doing in each step, as some things were too surprising (e.g., `weaver-kube deploy` building a local docker image).
=> Fix the wea-dev-apply command to push the app image only after building

app/services/sales-api/main.go, business/web/v1/mid/cors.go, business/web/v1/mux/mux.go
allows multiple domains for CORS
=> allows multiple domains for CORS

makefile
Using a watch this way will refresh the output instead of logging every state change. After seeing you're lectures, I think this is the functionality you actually wanted.
=> Update make dev status command

app/services/sales-api/tests/model_test.go
=> clean up model_test

app/services/sales-api/tests/home_seed_test.go, app/services/sales-api/tests/model_test.go, app/services/sales-api/tests/product_seed_test.go, app/services/sales-api/tests/user_seed_test.go, app/services/sales-api/tests/vproduct_seed_test.go, business/data/dbtest/dbtest.go
do you think we can remove pass from token?
=> remove Pass rom token

README.md, app/services/sales-api/tests/model_test.go
=> Cleanreadme

makefile
small fixes on the makefile in the Class Stuff section
=> fix makefile class stuff

makefile
With this, images are now pulled in parallel.
When loading them into kind, this will also be done in parallel.
=> Speed up pulling images locally and loading them into kind

makefile
=> dev-brew: instal -> install

app/domain/homeapp/homeapp.go, app/domain/productapp/productapp.go, app/domain/userapp/userapp.go, business/domain/homebus/model.go, business/domain/productbus/productbus.go, business/domain/userbus/userbus.go, business/domain/vproductbus/vproductbus.go
=> Fix Typo in Comments

CONTRIBUTORS, makefile
The pull request adds a help command to Makefile.
=> Add help command to makefile

CONTRIBUTORS, foundation/docker/docker.go
Replace manual string manipulation with in-template formatting for cleaner, more efficient code.
=> Refactor: Improve JSON formatting in Docker inspect template.

app/domain/authapp/authapp.go, app/domain/homeapp/homeapp.go, app/domain/productapp/productapp.go, app/domain/userapp/userapp.go, app/domain/vproductapp/filter.go, app/domain/vproductapp/vproductapp.go, app/sdk/errs/errs.go
This PR addresses two issues:
* Rename `NewFieldsError` to `NewFieldErrros`,
* Fix filter validation issue with `vproductapp` filtering stage.
=> Fix typo and filtering

makefile
added new command for fresh start -> dev-run: build dev-up dev-load dev-apply
edited dev-shell command
added dev-auth-shell for AUTH app
added dev-db-shell for database
=> chore(makefile): added new dev run and shell commands

api/frontends/admin/package.json, api/frontends/admin/pnpm-lock.yaml, api/frontends/admin/src/components/UI/failure-dialog.vue, api/frontends/admin/src/components/UI/success-dialog.vue, api/frontends/admin/src/components/Users/UserHomesTable.vue, api/frontends/admin/src/components/Users/UsersEdit.vue, api/frontends/admin/src/components/Users/UsersHomeTableActions.vue, api/frontends/admin/src/components/Users/UsersTable.vue, api/frontends/admin/src/components/Users/UsersTableActions.vue, api/frontends/admin/src/layouts/default/View.vue, api/frontends/admin/src/plugins/vuetify.js
Frontend is quite buggy, but it doesn't work out of the box at the moment. 
This bunch of short commits make it alive.
=> Make frontend great again!

app/sdk/apitest/apitest.go, business/domain/auditbus/auditbus_test.go, business/domain/homebus/homebus_test.go, business/domain/productbus/productbus_test.go, business/domain/userbus/userbus_test.go, business/domain/vproductbus/vproduct_test.go, business/sdk/unittest/model.go, business/sdk/unittest/unittest.go
This PR addresses two issues:
1. Fix typo in package name,
2. Use functional options pattern to make tests receive options.  For example, we can use this when we need to temporarily skip a test.
=> Feat: Test Options

business/domain/userbus/stores/usercache/usercache.go
=> fix: return store configured for transaction
