ardanlabs/service

- .gitignore
- README.md
- cmd/sales-admin/main.go
- cmd/sales-api/handlers/routes.go
- cmd/sales-api/main.go
- docker-compose.yaml
- dockerfile
- makefile
This PR does a few final things to ensure the service is runnable.
1. Updates the makefile to work with the single-dockerfile approach. Previously `docker-compose up` knew how to build the images but now it doesn't.
2. Adds a second command `sales-admin` which holds two administrative scripts for running the service.
- `--cmd keygen` generates a private key for signing auth tokens. This is preferable over using `openssl` or something on the command line because not everyone has that installed.
- `--cmd useradd` which creates an initial admin user. If you use `make admin` it creates a user with email `admin@example.com` and password `gophers`. If you want to use something else you can run it yourself like
```
go run ./cmd/sales-admin/main.go --cmd useradd --user_email jacob@ardanlabs.com …
```
> Update makefile for build, add admin command

- internal/platform/web/validation.go
Unmarshal not returning any error if field name incorrect or not available. Go version 1.10 added a new method DisallowUnknownFields which we can use to return error for unknown JSON fields.
> Unmarshal - return error if input fields not match

- cmd/sales-api/main.go
- cmd/sidecar/metrics/main.go
- cmd/sidecar/tracer/main.go
We already aren't using graceful shutdown for these services as they are internal only. Similarly we don't need custom timeouts etc.
> Use the simple http.ListenAndServe for debug services

- cmd/sales-api/handlers/routes.go
- internal/platform/web/middleware.go
- internal/platform/web/web.go
Ranging over middleware from beginning to end when building handler chains has the effect of *wrapping* them in the order they are listed but it means the resulting middleware handlers are executed in *reverse* of the order they are shown in the code. This always confused me especially when we have middleware that must be ran after another such as the auth `HasRole` mw which must be ran after the `Authenticate` mw. In the route listing we have to put the `HasRole` first to ensure it is executed after `Authenticate`.
I changed `wrapMiddleware` to loop backwards through the list and wrap in that order. This means when a request comes in then the middleware handlers will be first encountered in the order they are listed in source code.
Also as a minor change I swapped the arguments of …
> Apply middleware so they are executed in the order they are listed

- cmd/sales-api/handlers/routes.go
- cmd/sidecar/tracer/handlers/routes.go
- internal/mid/auth.go
- internal/mid/errors.go
- internal/mid/logger.go
- internal/mid/metrics.go
- internal/mid/mid.go
This PR brings the MW changes we made in `service-training` into the main project. It is functionally the same as what we had already reviewed though there are necessarily minor differences because of the other changes in `service-training` that have not yet been merged here.
> Use a single type to hold state for all middleware

- cmd/sales-api/handlers/routes.go
- internal/mid/errors.go
- internal/mid/metrics.go
- internal/mid/panics.go
- internal/platform/web/web.go
This PR removes the `Error bool` field from the `web.Values` struct type. Rather than using this flag variable on each request we can just count errors as they bubble up the middleware chain.
To accomplish this, the "Metrics" middleware is moved so it starts after and finishes before the Error middleware.
Furthermore this PR moves the 19 line panic recovery func from the Error mw into a 7 line deferred func in its own middleware.
> Simplify panic handling in middleware

- cmd/sales-api/main.go
- cmd/sidecar/metrics/main.go
- cmd/sidecar/metrics/publisher/datadog/datadog.go
- cmd/sidecar/metrics/publisher/expvar/expvar.go
- cmd/sidecar/metrics/publisher/publisher.go
- internal/mid/metrics.go
- internal/platform/auth/authenticator.go
- internal/platform/auth/authenticator_test.go
- internal/platform/auth/claims.go
- internal/platform/db/db.go
- internal/platform/docker/docker.go
- internal/platform/flag/doc.go
- internal/platform/trace/trace_test.go
- internal/platform/web/request.go
- internal/platform/web/response.go
- internal/product/product.go
- internal/user/user.go
Avoid code duplication when creating http client by extracting into a factory method under platform/web package.
Fix DualStack deprecated property.
Fix typos.
> Extract http client factory into platform/web package and fix typos.

- internal/platform/web/response.go
This function was added in the recent PR but it is never used. I looked around and there are only 2 places in the code base we might use this function.
> Remove unused error function

- cmd/sales-admin/main.go
- cmd/sales-api/main.go
- cmd/sidecar/metrics/main.go
- cmd/sidecar/tracer/main.go
- internal/platform/conf/README.md
- internal/platform/conf/conf.go
- internal/platform/conf/conf_test.go
- internal/platform/conf/doc.go
- internal/platform/conf/sources.go
- internal/platform/conf/usage.go
This PR does two things
1. Include the env var namespace in the usage output
2. Removes sorting of fields. They are instead printed in the order they appear in the config struct which provides a more logical grouping of options and lets the end user control it.
For `sales-admin` and `sales-api` the resulting usage strings look like this:
```
~ $ sales-admin -h
Usage: sales-admin [options] [arguments]
OPTIONS
--cmd/$SALES_CMD                                      <string>
--db-user/$SALES_DB_USER                              <string>  (default: postgres)
--db-password/$SALES_DB_PASSWORD                      <string>  (noprint,default: postgres)
--db-host/$SALES_DB_HOST                              <string>  (default: localhost)
--db-name/$SALES_DB_NAME                              <string> …
```
> Update conf usage

- cmd/sales-api/handlers/routes.go
- cmd/sidecar/tracer/handlers/routes.go
- internal/mid/panics.go
We are not logging Go's stack trace for the panic. This is very important.
> adding the logging of Go's stack trace

- cmd/sales-api/main.go
When serverError reads off the err channel it is not necessarily just a startup error, so the message should be more generic.
> Make server error message more accurate

- dockerfile.sales-api
The comment in the Dockerfile says the admin tool changes often, but it is actually the other way around. Added the word 'not'.
> Update small typo in dockerfile comment

- app/sales-api/tests/user_test.go
A small fix on a misnaming of test functions in the sales-api test suite.
postUser403 is supposed to test 403 Forbidden by the service,
but it was actually testing 401 Unauthorized and expecting
a 401 response to pass.
Similarly, postUser401 is supposed to test 401 Unauthorized,
but it was actually testing 403 Forbidden and expecting a
403 response to pass.
> sales-api/tests: fix backwards test names.

- README.md
Researching what a solid extension repo looks like to prepare a comparable emacs starter guide, I noticed [microsoft/vscode-go](https://github.com/microsoft/vscode-go) has been archived.
> Replace archived vscode-go link with new version.

- business/data/user/user.go
Hi Ardan Labs Team,
I think there's a little mistake on package `github.com/ardanlabs/service/business/data/user` , exactly on trace log. Here's the details:
Before fixing: `ctx, span := trace.SpanFromContext(ctx).Tracer().Start(ctx, "internal.data.user.create")`
After fixing: `ctx, span := trace.SpanFromContext(ctx).Tracer().Start(ctx, "business.data.user.create")`
Thank you.
> Fix Trace Log for Business User Data

- CONTRIBUTORS
- app/sales-admin/commands/useradd.go
- app/sales-admin/main.go
**bug**: useradd command was missing name parameter, causing the validation on user.Create to fail.
I've made the necessary changes to sort this out.
> fix sales-admin useradd command - missing name parameter

- app/sales-admin/commands/migrate.go
**bug**: when running `make run` the migration is ran directly after the containers spin up, most of the time this throws an error as the database is not ready to accept requests yet.
`make run` output without db status check:
```bash 
(base) MacBook-Pro:service si.chan$ make run
docker-compose -f zarf/compose/compose.yaml -f zarf/compose/compose-config.yaml up --detach --remove-orphans
Creating network "compose_shared-network" with driver "bridge"
Creating sales_db ... done
Creating zipkin   ... done
Creating sales-api ... done
Creating metrics   ... done
go run app/sales-admin/main.go migrate
ADMIN : 2021/03/21 10:49:11.948744 main.go:74: main: Config :
--svn=develop
--desc=copyright information here
--args=[migrate]
--db-user=postgres
--db-password=xxxxxx
--db-host=0.0.0.0 …
```
> fix - add db status check to ensure db is ready for migration

- CONTRIBUTORS
- foundation/keystore/keystore.go
`strings.TrimRight("develop.pem", ".pem")` results in "develo" because any of the matching characters on the right are trimmed
> Replaces TrimRight with TrimSuffix

- app/sales-api/main.go
- app/sidecar/metrics/main.go
The `os.Interrupt` variable is really just `syscall.SIGINT`. Using `syscall.SIGINT` is a bit more readable since it matches `syscall.SIGTERM` next to it.
When I first went through the Ultimate Service course I wondered why `os.Interrupt` was being used instead of `syscall.SIGINT`.
> Use SIGINT from syscall package

- makefile
A simple request to replace the default smart quotes with simple quotes as some terminals do not support smart quote characters, and they can cause strange errors in scripts.
macos defaults to smart quotes, this command snippet will disable them globally:
```
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
```
> replacing smart quotes with simple quotes

- app/services/sales-api/handlers/v1/productgrp/productgrp.go
Import alias `userProduct` was renamed to `productCore`, which better describes the package and follows the pattern in `usergrp`.
> Fix for product core alias typo

- app/services/sales-api/handlers/v1/productgrp/productgrp.go
- business/core/product/product.go
- business/web/v1/v1.go
Authorization for product `update` and `delete` actions went missing after the recent `core` updates. 
This fix adds both checks back into the handlers layer.
> [Fix] Add back authorization checks for product update & delete. 

- CONTRIBUTORS
- business/sys/database/database.go
Wrong logger method was used for database transactions - as a result, the printed message lacks delimiters.
> [Fix] Logger prints messages without spaces.

- makefile
The two shell commands `kind-shell` and `gcp-shell` filter for two different keys. The correct version should grep for `sales` and not `app`.
> kind-shell command should grep for sales

- makefile
- zarf/docker/dockerfile.metrics
- zarf/docker/dockerfile.sales-api
- Following security best practices, both **sales-api** and **metrics** docker images are refactored to run as non-root user.
- Fixed broken `make kind-shell` by changing the container name to the proper one.
> runs images as non-root user

- business/web/v1/mid/cors.go
- foundation/web/web.go
`web.App` is missing an `OptionHandler` - this PR adds it and updates the CORS middleware docs.
> [Fix] Added OptionHandler on web.App & updated CORS documentation.

- zarf/docker/dockerfile.metrics
found this line duplicate
```
COPY . /service
```
> omit duplicate copy in metrics docker file

- foundation/web/web.go
Gracefully handle write errors due to the client's connection being disconnected during a large file/data being written to the response at the same time.
`business/web/v1/mid/errors.go` doesn't seem like a good place because of the following:
https://github.com/ardanlabs/service/blob/master/business/web/v1/mid/errors.go#L63-L66
will then call:
https://github.com/ardanlabs/service/blob/master/foundation/web/response.go#L39-L42
which ends up writing to the `http.ResponseWriter` anyways. Hence, when the call stack returns, the common denominator is to have `web.go` handle the error.
This will prevent what would currently cause a signaling of a "shutdown" and causing and outage, and instead, we now catch the error and stop the signaling of the shutdown. We should be "fine" with approach …
> handle error that occurs when the client disconnects while the http.ResponseWriter is about/being to be written to

- README.md
The education links point to a missing page (Issue #233).
> Updated ArdanLabs education links

- CONTRIBUTORS
- foundation/docker/docker.go
when starting a container, for example redis, if there is any typo when passing port argument, StartContainer will produce an error to caller however this image is running in the background we just couldn't extract ip, so as we created this container successfully, we should stop it when an error is happening after container started.
> remove container leak

- CONTRIBUTORS
- zarf/k8s/base/sales/base-sales.yaml
- zarf/k8s/dev/sales/dev-sales-patch-deploy.yaml
The value is rounded to the next int. E.g. for 2400m GOMAXPROCS will be 3.
More values that can be used can be found here: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/
> Automatically set the GOMAXPROCS from the pods' limits.cpu value

- CONTRIBUTORS
- makefile
The command `telepresence helm install` runs an init container `curlimages/curl:8.1.1`. Adding this image to the dependency variables and `dev-docker` and `dev-up` commands in the `makefile`
> Add curl for telepresence helm install

- app/services/sales-api/v1/cmd/cmd.go
The context should be propagated on shutdown
> use one ctx on shutdown for cmd.go

- makefile
For people using podman instead of docker, these minor changes should make everything work out of the box.
Mainly it comes from the defaults that docker sets, where the default repo is docker.io, whereas podman does not set that as a default. the podman-driver is currently, experimental.
As for usage, this should not require anything extra from podman-users at all, even though I added an extra makefile-command `dev-save-load`, but it is not required.
> Podman fixes

- .circleci/config.yml
- foundation/docker/docker.go
- makefile
- zarf/k8s/dev/sales/kustomization.yaml
This patch adds support for running service using Podman. There are a few notable changes that were required to enable Podman support, described below.
Podman keeps `HostIP` empty instead of using `0.0.0.0`. This behavior required an update to `extractIPPort`. More information in https://github.com/containers/podman/issues/17780.
Podman prefers to use fully-qualified container images (i.e., `example.com/foo/bar:latest`) but will perform [short-name aliasing](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md#short-name-aliasing) for unqualified container images. When an unqualified image such as `foo/bar:latest` is loaded into a kind cluster it will be stored as `localhost/foo/bar:latest`.
Using backticks for command substitution isn't POSIX compatible. …
> feat: support podman

- CONTRIBUTORS
- foundation/validate/errors.go
add len to method Fields returns the fields that failed validation
> chore(errors): add len to returns the fields

- makefile
Hello, thanks for this starter-kit!
It seems there are typos in `make dev-gotooling` command causing such error:
```
go: honnef.co/go/tools/programs/staticcheck@latest: module honnef.co/go/tools@latest found (v0.4.7), but does not contain package honnef.co/go/tools/programs/staticcheck
make: *** [makefile:141: dev-gotooling] Error 1
```
> Fix make dev-gotooling

- makefile
Viewing `makefile` on Github reveals that indentation is mixed, using both spaces and tab characters. This PR addresses this by consistently using the tab character (the dominant indentation in the file).
> makefile: use tab indentation consistently

- .gitignore
- CONTRIBUTORS
- makefile
Current Makefile is pointing to the wrong path for frontend.
Gitignore also configured to point to the existing frontend path.
> Fix issue with admin frontend

- foundation/web/web.go
CORS format only allow one Access-Control-Allow-Origin header
Reference
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
> fix Access-Control-Allow-Origin header

- app/domain/vproductapp/filter.go
- app/domain/vproductapp/model.go
Moved the `queryparams` struct to be next to the `parseQueryParams` function to maintain consistency with other domains in the app layer.
> Move queryparams

- app/domain/homeapp/model.go
- app/domain/productapp/model.go
- app/domain/tranapp/model.go
- app/domain/userapp/model.go
- app/sdk/errs/validate.go
In the first commit, I used the newly added `Add` method of `FieldErrors` to append errors to the collection.
I'm not sure if I'm doing the right thing in the second commit. Since we're using the result of `Validate` function inside `web.Decode` function, and eventually this result is used at the app layer&mdash;like what comes next&mdash; I thought we could've wrapped any intermediate errors  and only then at the `app` layer, put them inside an `errs.Error`:
```go
func (a *app) create(ctx context.Context, r *http.Request) web.Encoder {
...
if err := web.Decode(r, &app); err != nil {
return errs.New(errs.InvalidArgument, err)
}
...
}
```
> Error Handling in Validate Function

- foundation/otel/otel.go
- foundation/web/context.go
This MR removes duplicated option sent to `sdktrace.WithBatcher()` function.
> Duplicated TraceProviderOption

- foundation/web/web.go
We've already been handling CORS logic at [web.go:147](https://github.com/ardanlabs/service/blob/1fddab71862770ede5781cb7417b09a7c71a064f/foundation/web/web.go#L147) using a middleware. So I removed the part which was repeating the same logic.
> Remove Duplicated CORS Logic

- app/sdk/authclient/authclient.go
removed deprecated DualStack of net.Dialer in authclient sdk and added comments.
Reference:
[net.Dialer pkg.go.dev](https://pkg.go.dev/net#Dialer):
```
// DualStack previously enabled [RFC 6555](https://rfc-editor.org/rfc/rfc6555.html) Fast Fallback
// support, also known as "Happy Eyeballs", in which IPv4 is
// tried soon if IPv6 appears to be misconfigured and
// hanging.
//
// Deprecated: Fast Fallback is enabled by default. To
// disable, set FallbackDelay to a negative value.
DualStack [bool](https://pkg.go.dev/builtin#bool)
// FallbackDelay specifies the length of time to wait before
// spawning a [RFC 6555](https://rfc-editor.org/rfc/rfc6555.html) Fast Fallback connection. That is, this
// is the amount of time to wait for IPv6 to succeed before
// assuming that IPv6 is …
```
> chore: removed deprecated DualStack of net.Dialer in authclient sdk

- app/sdk/auth/auth.go
This pull request includes changes to the `Authenticate` method in the `auth.go` file to improve error handling by removing unnecessary error wrapping. 
Error handling improvements:
* [`app/sdk/auth/auth.go`](diffhunk://#diff-a9ea36481325de4a7eb18b87a3dae7a8f3d7d4718c01905015be9a77f0e012b0L125-R130): Modified the `Authenticate` method to return plain error messages instead of wrapping errors with `fmt.Errorf` when the `kid` is missing or malformed.
> Error handling improvements

- zarf/k8s/dev/tempo/dev-tempo.yaml
I discovered the issue when there was no tracing in Tempo after upgrading to 2.7.0. This pull request addresses the issue where the OpenTelemetry Collector receiver defaults to binding on `localhost` instead of `0.0.0.0` after upgrading to version 2.7.0. As a result of this change, Tempo installations running in Docker or other container environments must update their listener addresses to continue receiving data.
**Background:**
- Issue: [#4465](https://github.com/open-telemetry/opentelemetry-collector/issues/4465)
- ChangeLog: [#Upgrade_Considerations](https://grafana.com/docs/tempo/latest/release-notes/v2-7/#opentelemetry-collector-receiver-listens-on-localhost-by-default)
- After the upgrade, the receivers now default to `localhost:4317` and `localhost:4318` instead of `0.0.0.0:4317` …
> fix(tempo): added hostname and endpoints to support connections in 2.7.0

- foundation/otel/sampler.go
HTTP semantic conventions changed.
http.target attribute was split into two attributes, url.path and url.query.
https://github.com/open-telemetry/semantic-conventions/blob/v1.36.0/docs/http/http-spans.md#http-client-server-example
> Refactor sampler to use combined `url.path` and `url.query` for endpoint matching.
